name: cilviewer_dev
channels:
  - ccpi
  - paskino
  - conda-forge
dependencies:
    - python
    - numpy
    - vtk >=9.0.3
    - pyside2
    - eqt
    - importlib_metadata    # [py<38]
    - h5py
    - cil-data >=22.0.0
    - pillow