name: cilviewer
channels:
  - ccpi
  - conda-forge
dependencies: 
    - python
    - numpy
    - vtk
    - pyside2
    - eqt>=2.0.0
    - importlib_metadata    # [py<38]
    - h5py
    - pillow
    - pyyaml
    - schema
