name: cilviewer_dev
channels:
  - ccpi
  - conda-forge
dependencies: 
    - python
    - numpy
    - vtk
    - pyside2
    - eqt=1.0.0
    - importlib_metadata    # [py<38]
    - h5py
    - pillow
    - pyyaml
    - schema
    - cil-data=22.0.0
