name: cilviewer_dev
channels:
  - ccpi
  - conda-forge
dependencies: 
    - python
    - numpy
    - vtk=9.0.3
    - pyside2
    - eqt>=0.7.1
    - importlib_metadata    # [py<38]
    - h5py
    - cil-data=22.0.0
    - pillow
    - schema
