package:
  name: ccpi-viewer
  version: 20.07.2


build:
  preserve_egg_dir: False

  entry_points:
    - CILViewerLaunch = ccpi.viewer.standaloneQT:main
    - triViewerLaunch = ccpi.viewer.triWidgetQT:main

  number: 0
  
requirements:
  build:
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - python 
    - setuptools
    - numpy
 
  run:
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - python
    - numpy
    - vtk ==8.1.2
    - natsort
    - pyqt >=5.6
    - matplotlib

about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Core Imaging Library (Viewer)'
