package:
  name: ccpi-viewer
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ../../../

build:
  skip: True # [py==38 and np==115]
  preserve_egg_dir: False 
  number: {{ GIT_DESCRIBE_NUMBER }}

  
requirements:
  build:
    - python
    - numpy {{ numpy }} 
 
  run:
    - python
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - vtk ==8.1.2
    - pyside2
    - eqt

about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Core Imaging Library (Viewer)'
