package:
  name: ccpi-viewer
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ../../../

build:
  skip: True # [py==38 and np==115]
  preserve_egg_dir: False 
  number: {{ GIT_DESCRIBE_NUMBER }}
  noarch: python
  entry_points:
    - web_cilviewer = ccpi.web_viewer.web_app:main
  
test:
  requires:
    - pillow
  source_files:
    - ./Wrappers/Python/test

  commands:
    - ls # [not win]
    - python -c "import os; print ('TESTING IN THIS DIRECTORY' , os.getcwd())" # [not win]
    - python -m unittest discover -s Wrappers/Python/test -v # [not win]
  
requirements:
  build:
    - python {{ python }}
    - vtk {{ vtk }}
 
  run:
    - python {{ python }}
    - numpy
    - vtk {{ vtk }}
    - pyside2
    - eqt
    - importlib_metadata    # [py<38]
    - h5py
    - cil-data >=22.0.0

about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Core Imaging Library (Viewer)'
