package:
  name: ccpi-viewer
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ../../../

build:
  skip: True # [py==38 and np==115]
  preserve_egg_dir: False 
  number: {{ GIT_DESCRIBE_NUMBER }}
  noarch: python
  entry_points:
    - resample = ccpi.viewer.cli.resample:main
    - web_cilviewer = ccpi.web_viewer.web_app:main
    - cilviewer = ccpi.viewer.standalone_viewer:main
  
test:
  requires:
    - ccpi::cil-data=22.0.0
    - pillow
    - pytest
    - pyside2
    - eqt>=2.0.0
  source_files:
    - ./Wrappers/Python/test

  commands:
    - python -m pytest Wrappers/Python/test # [not win]
  
requirements:
  build:
    - python
    - vtk
    - setuptools
 
  run:
    - python
    - numpy
    - vtk
    - h5py
    - pyyaml
    - schema
    - qtpy

about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Core Imaging Library (Viewer)'
