package:
  name: ccpi-viewer
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ../../../

build:
  skip: True # [py==38 and np==115]
  preserve_egg_dir: False 
  number: {{ GIT_DESCRIBE_NUMBER }}
  noarch: python
  
test:
  source_files:
    - ./Wrappers/Python/test

  commands:
    - python -c "import os; print ('TESTING IN THIS DIRECTORY' , os.getcwd())"
    - python -m unittest discover -s Wrappers/Python/test

  
requirements:
  build:
    - python
 
  run:
    - python
    - numpy
    - vtk >=9.0.3 
    - pyside2
    - eqt

about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Core Imaging Library (Viewer)'
