package:
  name: ccpi-viewer
  version: {{ environ['CIL_VERSION'] }}


build:
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION

  entry_points:
    - CILViewerLaunch = ccpi.viewer.standaloneQT:main
    - triViewerLaunch = ccpi.viewer.triWidgetQT:main
#  number: 0
  
requirements:
  build:
    - python
    - setuptools
 
  run:
    - python
    - numpy
    - vtk
    - natsort
    - pyqt


	
about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Core Imaging Library (Viewer)'
