package:
  name: ccpi-viewer
  version: 21.0.0


build:
  preserve_egg_dir: False
  number: 2
  
requirements:
  build:
    - python
    - numpy {{ numpy }} 
 
  run:
    - python
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - vtk
    - pyside2
    - eqt

about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Core Imaging Library (Viewer)'
