package:
  name: ccpi-viewer
  version: {{ environ['CIL_VERSION'] }}


build:
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION   
#  number: 0
  
requirements:
  build:
    - python
    - setuptools
 
  run:
    - python
    - numpy
    - vtk


	
about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Core Imaging Library (Viewer)'
